/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.createGUI;

import com.mycompany.finaltermproject.storageUI;
import com.sqlConnection.Function;
import com.sqlConnection.JDBCUtil;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author trieu
 */
public class EditProduct extends javax.swing.JFrame {

    String id = null;
    String productName = null;
    int importPrice = 0;
    int sellPrice = 0;
    String origin = null;
    String supplier = null;
    String productType = null;
    int quantity = 0;

    /**
     * Creates new form AddProduct
     */
    public EditProduct(String productId) throws SQLException {
        initComponents();
        Connection con = JDBCUtil.getConnection();
        Statement st = null;
        try {
            st = con.createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(EditProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet productInfo = st.executeQuery("SELECT * FROM PRODUCTS WHERE ID = '" + productId + "'");
        if (productInfo.next()) {
            id = productInfo.getString("id");
            productName = productInfo.getString("product_name");
            importPrice = productInfo.getInt("import_price");
            sellPrice = productInfo.getInt("sell_price");
            origin = productInfo.getString("origin");
            supplier = productInfo.getString("supplier");
            productType = productInfo.getString("product_type");
            quantity = productInfo.getInt("quantity");
        }

        JDBCUtil.closeConnection(con);
        idTF.setText(id);
        idTF.setEditable(false);
        idTF.setBackground(Color.GRAY);
        productTypeCBB.setSelectedItem(productType);
        productTypeCBB.setEnabled(false);
        productNameTF.setText(productName);
        importPriceTF.setText(String.valueOf(importPrice));
        sellPriceTF.setText(String.valueOf(sellPrice));
        originTF.setText(origin);
        supplierTF.setText(supplier);
        quantityTF.setText(String.valueOf(quantity));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        idTF = new javax.swing.JTextField();
        productNameTF = new javax.swing.JTextField();
        sellPriceTF = new javax.swing.JTextField();
        originTF = new javax.swing.JTextField();
        quantityTF = new javax.swing.JTextField();
        productTypeCBB = new javax.swing.JComboBox<>();
        backButton = new javax.swing.JButton();
        importPriceTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        supplierTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grocery Store");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(262, 113));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHỈNH SỬA SẢN PHẨM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(234, 234, 234))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tên:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Giá bán:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Giá nhập:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Xuất xứ:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Quantity:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Product type");

        resetButton.setBackground(new java.awt.Color(102, 204, 0));
        resetButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(51, 204, 255));
        addButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Xác nhận");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        idTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idTF.setMinimumSize(new java.awt.Dimension(64, 25));
        idTF.setPreferredSize(new java.awt.Dimension(64, 25));
        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        productNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productNameTF.setMinimumSize(new java.awt.Dimension(64, 25));
        productNameTF.setPreferredSize(new java.awt.Dimension(64, 25));

        sellPriceTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sellPriceTF.setPreferredSize(new java.awt.Dimension(64, 25));

        originTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        originTF.setPreferredSize(new java.awt.Dimension(70, 25));
        originTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originTFActionPerformed(evt);
            }
        });

        quantityTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantityTF.setPreferredSize(new java.awt.Dimension(64, 25));
        quantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTFActionPerformed(evt);
            }
        });

        productTypeCBB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        productTypeCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose type", "Đồ uống", "Bánh ngọt", "Đồ ăn nhẹ", "Gia vị", "Hóa mỹ phẩm" }));
        productTypeCBB.setPreferredSize(new java.awt.Dimension(72, 25));
        productTypeCBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTypeCBBActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 102, 102));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Hủy bỏ");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        importPriceTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        importPriceTF.setMinimumSize(new java.awt.Dimension(64, 25));
        importPriceTF.setPreferredSize(new java.awt.Dimension(64, 25));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Nhà cung ứng:");

        supplierTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierTF.setPreferredSize(new java.awt.Dimension(70, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(558, 558, 558))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(productTypeCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(idTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productNameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sellPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(importPriceTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(originTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(supplierTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(productNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(importPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sellPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(originTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(supplierTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productTypeCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(quantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try {
            Connection con = JDBCUtil.getConnection();
            //PreparedStatement pr = con.prepareStatement("INSERT INTO LOGIN (USERNAME,PASSWORD,SEX,MOBILE_NUMBER) VALUE (?,?,?,?)");
            PreparedStatement pr
                    = con.prepareStatement("UPDATE products SET product_name = ?, import_price = ?, sell_price = ?, "
                            + "origin = ?, supplier = ?, quantity = ? WHERE id = '" + id + "'");

            // Kiem tra 
            if (!productNameTF.getText().isEmpty() && !importPriceTF.getText().isEmpty() && !sellPriceTF.getText().isEmpty()
                    && !originTF.getText().isEmpty() && !supplierTF.getText().isEmpty() && !quantityTF.getText().isEmpty()) {

                //Tien hanh insert vao database
                pr.setString(1, productNameTF.getText());
                pr.setString(2, importPriceTF.getText());
                pr.setString(3, sellPriceTF.getText());
                pr.setString(4, originTF.getText());
                pr.setString(5, supplierTF.getText());
                pr.setString(6, quantityTF.getText());
//                switch (choice) {
//                    case "Foods":
//                        pr.setString(7, "Fo");
//                        break;
//                    case "Drinks":
//                        pr.setString(7, "Dr");
//                        break;
//                    case "Household appliances":
//                        pr.setString(7, "HA");
//                        break;
//                    case "Personal hygiene items":
//                        pr.setString(7, "HPI");
//                        break;
//                    case "Spices":
//                        pr.setString(7, "Sp");
//                        break;
//                    default:
//                        break;
//                }

                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Edit Product Successfully");
                storageUI storage = new storageUI();
                storage.setLocation(this.getX(), this.getY());
                storage.setVisible(true);
                this.dispose();
//                PreparedStatement pr1 = con.prepareStatement("INSERT INTO IMPORT_STATISTIC_SHEET (id, product_id, price, statistical_day) "
//                        + "VALUES (?,?,?,?)");
//                pr1.setString(1, idTF.getText());
//                pr1.setString(2, productNameTF.getText());
//                pr1.setString(3, sellPriceTF.getText());
//                LocalDate today = LocalDate.now();
//                String todayString = today.toString();
//                pr1.setString(4, todayString);
//                pr1.executeUpdate();
            } else {
                System.out.println(idTF.getText() + productNameTF.getText() + importPriceTF.getText() + sellPriceTF.getText()
                        + originTF.getText() + supplierTF.getText() + quantityTF.getText());
                JOptionPane.showMessageDialog(null, "Please insert all data");
                Function.checkTextField(productNameTF);
                Function.checkTextField(importPriceTF);
                Function.checkTextField(sellPriceTF);
                Function.checkTextField(originTF);
                Function.checkTextField(supplierTF);
                Function.checkTextField(quantityTF);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Something went wrong!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        storageUI storage = new storageUI();
        storage.setLocation(this.getX(), this.getY());
        storage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void quantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTFActionPerformed

    private void originTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originTFActionPerformed

    private void productTypeCBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTypeCBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTypeCBBActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        productNameTF.setText(productName);
        importPriceTF.setText(String.valueOf(importPrice));
        sellPriceTF.setText(String.valueOf(sellPrice));
        originTF.setText(origin);
        supplierTF.setText(supplier);
        quantityTF.setText(String.valueOf(quantity));
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EditProduct("1").setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EditProduct.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField idTF;
    private javax.swing.JTextField importPriceTF;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField originTF;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JComboBox<String> productTypeCBB;
    private javax.swing.JTextField quantityTF;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField sellPriceTF;
    private javax.swing.JTextField supplierTF;
    // End of variables declaration//GEN-END:variables
}
