/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.createGUI.importGUI;

import com.mycompany.finaltermproject.ImportUI;
import com.mycompany.HandlerClass.Function;
import com.sqlConnection.JDBCUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trieu
 */
public class ImportNoteDetail extends javax.swing.JFrame {

    DefaultTableModel choiseProductTableModel;
    String idPhieuNhap = null;

    /**
     * Creates new form AddProduct
     */
    public ImportNoteDetail() {
        initComponents();
        this.choiseProductTableModel = (DefaultTableModel) choiseProductTable.getModel();
        choiseProductTableModel.setRowCount(0);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public ImportNoteDetail(String id, String trangThai) {
        initComponents();
        idPhieuNhap = id;

        if (!trangThai.equals("0")) {
            confirmNoteBtn.setEnabled(false);
            killNoteBtn.setEnabled(false);
        } else {
            confirmNoteBtn.setEnabled(true);
            killNoteBtn.setEnabled(true);
        }

        this.choiseProductTableModel = (DefaultTableModel) choiseProductTable.getModel();
        choiseProductTableModel.setRowCount(0);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        String query = "SELECT * "
                + " FROM phieunhap p"
                + " Join ctphieunhap ctp "
                + " On p.ma_phieu_nhap = ctp.ma_phieu_nhap "
                + " Join products pr "
                + " On pr.id = ctp.ma_san_pham "
                + " Join nha_cung_cap ncp"
                + " On p.ma_nha_cung_cap = nha_cung_cap.ma_nha_cung_cap "
                + " Where ctp.ma_phieu_nhap = ?";

        try (Connection con = JDBCUtil.getConnection(); ResultSet resultSet = JDBCUtil.getResultSet(con, query, 1, id)) {
            if (resultSet.next()) {

                // Gán giá trị và tắt thay đổi
                idPhieuNhapTF.setText(resultSet.getString("p.ma_phieu_nhap"));
                idPhieuNhapTF.setEnabled(false);

                accountNameTF.setText(resultSet.getString("p.account_id"));
                accountNameTF.setEnabled(false);

                supplierNameTF.setText(resultSet.getString("ncp.ten_nha_cung_cap"));
                supplierNameTF.setEnabled(false);

                dateTF.setText(resultSet.getDate("p.thoi_gian").toString());
                dateTF.setEnabled(false);

                choiseProductTableModel.setRowCount(0);
                do {
                    // Get values from the selected row
                    int nextSTT = choiseProductTableModel.getRowCount() + 1; // STT tiếp theo
                    String productId = resultSet.getString("ctp.ma_san_pham");
                    String name = resultSet.getString("pr.product_name");
                    String importPrice = Function.dinhDangTien(resultSet.getInt("ctp.don_gia"));
                    String quantity = resultSet.getString("ctp.quantity");

                    Object[] row = {nextSTT, id, name, importPrice, quantity};
                    choiseProductTableModel.addRow(row);
                } while (resultSet.next());
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu !");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ImportNoteDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idPhieuNhapTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        accountNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        supplierNameTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        choisePane = new javax.swing.JScrollPane();
        choiseProductTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        killNoteBtn = new javax.swing.JButton();
        confirmNoteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grocery Store");
        setBackground(new java.awt.Color(204, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                backToImportUI(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setText("Mã phiếu nhập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 20);
        jPanel4.add(jLabel1, gridBagConstraints);

        idPhieuNhapTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idPhieuNhapTF.setText("1234");
        idPhieuNhapTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPhieuNhapTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 30, 20);
        jPanel4.add(idPhieuNhapTF, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setText("Nhân viên nhập:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 20);
        jPanel4.add(jLabel2, gridBagConstraints);

        accountNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accountNameTF.setText("Vũ Khoa");
        accountNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNameTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 30, 20);
        jPanel4.add(accountNameTF, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setText("Nhà cung cấp:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 20);
        jPanel4.add(jLabel4, gridBagConstraints);

        supplierNameTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        supplierNameTF.setText("Công ty TNHH Trung Kiên");
        supplierNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 30, 20);
        jPanel4.add(supplierNameTF, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel6.setText("Thời gian tạo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 10, 20);
        jPanel4.add(jLabel6, gridBagConstraints);

        dateTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dateTF.setText("Công ty TNHH Trung Kiên");
        dateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 30, 20);
        jPanel4.add(dateTF, gridBagConstraints);

        getContentPane().add(jPanel4);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        choisePane.setBackground(new java.awt.Color(255, 255, 255));

        choiseProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên sản phẩm", "Đơn giá", "Số lượng"
            }
        ));
        choiseProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choiseProductTableMouseClicked(evt);
            }
        });
        choisePane.setViewportView(choiseProductTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel9.add(choisePane, gridBagConstraints);

        getContentPane().add(jPanel9);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(51, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xuất PDF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 10);
        jPanel1.add(jButton1, gridBagConstraints);

        killNoteBtn.setBackground(new java.awt.Color(255, 102, 102));
        killNoteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        killNoteBtn.setForeground(new java.awt.Color(255, 255, 255));
        killNoteBtn.setText("Hủy bỏ");
        killNoteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        killNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                killNoteBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 10);
        jPanel1.add(killNoteBtn, gridBagConstraints);

        confirmNoteBtn.setBackground(new java.awt.Color(102, 204, 0));
        confirmNoteBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmNoteBtn.setForeground(new java.awt.Color(255, 255, 255));
        confirmNoteBtn.setText("Xác nhận");
        confirmNoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNoteBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 10);
        jPanel1.add(confirmNoteBtn, gridBagConstraints);

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 10);
        jPanel1.add(backBtn, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idPhieuNhapTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPhieuNhapTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPhieuNhapTFActionPerformed

    private void accountNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNameTFActionPerformed

    private void supplierNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTFActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void choiseProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choiseProductTableMouseClicked

    }//GEN-LAST:event_choiseProductTableMouseClicked

    private void dateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void killNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_killNoteBtnActionPerformed
        try (Connection con = JDBCUtil.getConnection(); PreparedStatement comfirmNote = con.prepareStatement("UPDATE phieunhap SET trang_thai = 2 WHERE ma_phieu_nhap = ?")) {

            comfirmNote.setString(1, idPhieuNhap);
            // Thực thi câu lệnh
            int rowsUpdated = comfirmNote.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Hủy phiếu thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy dòng cần cập nhật trong cơ sở dữ liệu.");
            }
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_killNoteBtnActionPerformed

    private void backToImportUI(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_backToImportUI
        this.dispose();
    }//GEN-LAST:event_backToImportUI

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void confirmNoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNoteBtnActionPerformed
        try (Connection con = JDBCUtil.getConnection(); PreparedStatement confirmNote = con.prepareStatement("UPDATE phieunhap SET trang_thai = 1 WHERE ma_phieu_nhap = ?"); PreparedStatement updateProductQuantity = con.prepareStatement(
                "UPDATE products p "
                + "SET p.quantity = p.quantity + ("
                + "    SELECT SUM(ct.quantity) "
                + "    FROM ctphieunhap ct "
                + "    WHERE ct.ma_phieu_nhap = ? AND ct.ma_san_pham = p.id"
                + ") "
                + "WHERE EXISTS ("
                + "    SELECT 1 "
                + "    FROM ctphieunhap ct "
                + "    WHERE ct.ma_phieu_nhap = ? AND ct.ma_san_pham = p.id"
                + ")"
        )) {

            // Gán giá trị cho tham số để xác nhận phiếu nhập
            confirmNote.setString(1, idPhieuNhap);

            // Thực thi câu lệnh xác nhận phiếu nhập
            int rowsUpdated = confirmNote.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Xác nhận phiếu nhập thành công!");

                // Gán giá trị cho tham số để cập nhật số lượng sản phẩm
                updateProductQuantity.setString(1, idPhieuNhap);
                updateProductQuantity.setString(2, idPhieuNhap);

                // Thực thi câu lệnh cập nhật quantity
                int productRowsUpdated = updateProductQuantity.executeUpdate();
                if (productRowsUpdated > 0) {
                    System.out.println("Cập nhật số lượng sản phẩm thành công! Số dòng bị ảnh hưởng: " + productRowsUpdated);
                } else {
                    System.out.println("Không có sản phẩm nào để cập nhật số lượng.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu nhập cần cập nhật trong cơ sở dữ liệu.");
            }

            // Đóng giao diện hiện tại sau khi xác nhận thành công
            this.dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }

    }//GEN-LAST:event_confirmNoteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportNoteDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ImportNoteDetail().setVisible(true);
            }
        });
    }

    // Hàm cập nhật lại STT
    @SuppressWarnings("empty-statement")
    private void updateSTT() {
        long totalPrice = 0;

        for (int i = 0; i < choiseProductTableModel.getRowCount(); i++) {
            choiseProductTableModel.setValueAt(i + 1, i, 0);// Cập nhật cột STT
            int quantity = Integer.parseInt((String) choiseProductTableModel.getValueAt(i, 4));  // Lấy giá trị ở cột "Số lượng"
            long price = Long.parseLong((String) choiseProductTableModel.getValueAt(i, 3));  // Lấy giá trị ở cột "Giá"
            totalPrice += quantity * price; // Cộng tổng tiền
        }

        // Định dạng tiền tệ
        NumberFormat currencyFormat = NumberFormat.getInstance();
        String formattedTotalPrice = currencyFormat.format(totalPrice);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNameTF;
    private javax.swing.JButton backBtn;
    private javax.swing.JScrollPane choisePane;
    private javax.swing.JTable choiseProductTable;
    private javax.swing.JButton confirmNoteBtn;
    private javax.swing.JTextField dateTF;
    private javax.swing.JTextField idPhieuNhapTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton killNoteBtn;
    private javax.swing.JTextField supplierNameTF;
    // End of variables declaration//GEN-END:variables
}
