/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finaltermproject;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.createGUI.importGUI.AddImportNote;
import com.mycompany.createGUI.salesInvoiceGUI.AddSalesInvoice;
import javax.swing.JFrame;

/**
 *
 * @author letri
 */
public class mainUI extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public mainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPasswordField1 = new javax.swing.JPasswordField();
        Menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        accountName = new javax.swing.JLabel();
        accountFunction = new javax.swing.JLabel();
        userPicture = new javax.swing.JLabel();
        chucNang = new javax.swing.JPanel();
        storageBtn = new javax.swing.JButton();
        createImportBtn = new javax.swing.JButton();
        returnInvoiceBtn = new javax.swing.JButton();
        salesBtn = new javax.swing.JButton();
        thongkeBtn = new javax.swing.JButton();
        salesInvoiceBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grocery Store");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        Menu.setLayout(new javax.swing.BoxLayout(Menu, javax.swing.BoxLayout.Y_AXIS));

        accountName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountName.setText("Vũ Khoa");

        accountFunction.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountFunction.setText("Quản lý");

        userPicture.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userPicture.setIcon(new FlatSVGIcon("./icon/man_50px.svg"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(userPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountFunction)
                    .addComponent(accountName))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(accountFunction)
                        .addGap(12, 12, 12)
                        .addComponent(accountName)))
                .addGap(41, 41, 41))
        );

        Menu.add(jPanel2);

        chucNang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chucNang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chucNang.setLayout(new java.awt.GridBagLayout());

        storageBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        storageBtn.setText("Sản phẩm");
        storageBtn.setMargin(new java.awt.Insets(2, 50, 3, 50));
        storageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storageBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        chucNang.add(storageBtn, gridBagConstraints);

        createImportBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createImportBtn.setText("Nhập hàng");
        createImportBtn.setMargin(new java.awt.Insets(2, 50, 3, 50));
        createImportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createImportBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(createImportBtn, gridBagConstraints);

        returnInvoiceBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        returnInvoiceBtn.setText("Phiếu trả hàng");
        returnInvoiceBtn.setMargin(new java.awt.Insets(2, 65, 3, 65));
        returnInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnInvoiceBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(returnInvoiceBtn, gridBagConstraints);

        salesBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salesBtn.setText("Bán hàng");
        salesBtn.setMargin(new java.awt.Insets(2, 50, 3, 50));
        salesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(salesBtn, gridBagConstraints);

        thongkeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        thongkeBtn.setText("Thống kê");
        thongkeBtn.setEnabled(false);
        thongkeBtn.setMargin(new java.awt.Insets(2, 30, 3, 30));
        thongkeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thongkeBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 0);
        chucNang.add(thongkeBtn, gridBagConstraints);

        salesInvoiceBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salesInvoiceBtn.setText("Hóa đơn");
        salesInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesInvoiceBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(salesInvoiceBtn, gridBagConstraints);

        importBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        importBtn.setText("Phiếu nhập");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(importBtn, gridBagConstraints);

        customerBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        customerBtn.setText("Khách hàng");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(customerBtn, gridBagConstraints);

        supplierBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        supplierBtn.setText("Nhà cung cấp");
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        chucNang.add(supplierBtn, gridBagConstraints);

        Menu.add(chucNang);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setEnabled(false);

        logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 0));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel3.add(logout);

        Menu.add(jPanel3);

        getContentPane().add(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StoreIconActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        CustomerReturnInvoiceGUI customerReturnInvoiceGUI = new CustomerReturnInvoiceGUI();
        customerReturnInvoiceGUI.setLocation(this.getX()+20,this.getY()+20);
        customerReturnInvoiceGUI.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void returnInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnInvoiceBtnActionPerformed

    }//GEN-LAST:event_returnInvoiceBtnActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        LoginUI lg = new LoginUI();
        lg.setLocation(this.getX(), this.getY());
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void salesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBtnActionPerformed
        AddSalesInvoice addSalesInvoice = new AddSalesInvoice();
        addSalesInvoice.setLocation(this.getX()+20,this.getY()+20);
        addSalesInvoice.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addSalesInvoice.setVisible(true);
    }//GEN-LAST:event_salesBtnActionPerformed

    private void createImportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createImportBtnActionPerformed
        AddImportNote addImportNote= new AddImportNote();
        addImportNote.setLocation(this.getX()+20, this.getY()+20);
        addImportNote.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addImportNote.setVisible(true);
    }//GEN-LAST:event_createImportBtnActionPerformed

    private void thongkeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thongkeBtnActionPerformed

    }//GEN-LAST:event_thongkeBtnActionPerformed

    private void storageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storageBtnActionPerformed
        storageUI storageUI= new storageUI();
        storageUI.setLocation(this.getX(), this.getY());
        storageUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_storageBtnActionPerformed

    private void salesInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesInvoiceBtnActionPerformed
        SalesInvoiceGUI salesInvoiceGUI = new SalesInvoiceGUI();
        salesInvoiceGUI.setLocation(this.getX(), this.getY());
        salesInvoiceGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesInvoiceBtnActionPerformed

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        ImportUI importGUI = new ImportUI();
        importGUI.setLocation(this.getX(), this.getY());
        importGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_importBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        CustomerGUI customerGUI = new CustomerGUI();
        customerGUI.setLocation(this.getX(), this.getY());
        customerGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        SupplierGUI supplierGUI = new SupplierGUI();
        supplierGUI.setLocation(this.getX(), this.getY());
        supplierGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_supplierBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel accountFunction;
    private javax.swing.JLabel accountName;
    private javax.swing.JPanel chucNang;
    private javax.swing.JButton createImportBtn;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton importBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton logout;
    private javax.swing.JButton returnInvoiceBtn;
    private javax.swing.JButton salesBtn;
    private javax.swing.JButton salesInvoiceBtn;
    private javax.swing.JButton storageBtn;
    private javax.swing.JButton supplierBtn;
    private javax.swing.JButton thongkeBtn;
    private javax.swing.JLabel userPicture;
    // End of variables declaration//GEN-END:variables
}
